version: '3'
services:
  leather-shop:
    container_name: "leather-shop"
    image: leather-shop
    network_mode: host
    restart: on-failure
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - LEATHER_APP_PORT
      - LEATHER_DB_HOST
      - LEATHER_DB_PORT
      - LEATHER_DB_USER
      - LEATHER_DB_PASSWORD
      - LEATHER_DB_DATABASE
      - JWT_SECRET
      - JWT_ACCESS_TTL
      - JWT_REFRESH_TTL

  db:
    image: postgres:latest
    container_name: "leather-db"
    environment:
      POSTGRES_USER: ${LEATHER_DB_USER}
      POSTGRES_PASSWORD: ${LEATHER_DB_PASSWORD}
      POSTGRES_DB: ${LEATHER_DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - leather-db-data:/var/lib/postgresql/data

volumes:
  leather-db-data:
