version: '3'
services:
  db:
    image: custom-postgres
    container_name: "leather-db"
    environment:
      POSTGRES_USER: leather
      POSTGRES_PASSWORD: ef4t_A7yyU
      POSTGRES_DB: leather_base
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  leather-shop:
    container_name: "leather-shop"
    image: leather-shop
    restart: on-failure
    stdin_open: true
    tty: true
    depends_on:
      - db